services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PORT=${REDIS_PORT:-6379}

  postgres:
    image: postgres:13
    container_name: postgres_container
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-calendso}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  postgres_data: